---
title: "update_crowns_file"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{update_crowns_file}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, 	message = FALSE, warning = FALSE, results = "hide"}

library(SHPcrownsfile)
library(sf)
library(tidyverse)
library(readxl)
```



```{r, message=FALSE, warning=FALSE, paged.print=FALSE, results = 'hide'}
old_shp <- read_sf(system.file("gpkg/old_version.gpkg", package = 'SHPcrownsfile'))
new_shp <- read_sf(system.file("gpkg/gpkg_from_tablet.gpkg", package = 'SHPcrownsfile'))

# Le crs doit être en UTM
new_shp_corrected <- get_correct_id(new_shp = new_shp, 
               old_shp = old_shp, 
               crs = 'epsg:32633')
```

# The new sf object with the id corrected
```{r, message=FALSE, warning=FALSE, paged.print=FALSE}
head(new_shp_corrected$corrected_shp) 
```
# The id that have been corrected using the id_n
```{r, message=FALSE, warning=FALSE, paged.print=FALSE}
new_shp_corrected$correct_id_by_idn
```
# The id that have been corrected using the centroid
```{r, message=FALSE, warning=FALSE, paged.print=FALSE}
new_shp_corrected$correct_id_by_geom
```


```{r}
gil <- read_xlsx(system.file("xlsx/extract_bouamir_observatory_10_2024.xlsx", package = 'SHPcrownsfile'))
sf <- new_shp_corrected$corrected_shp
# Check les ids manquants
sf$id[!sf$id %in% gil$id]
gil$id[!gil$id %in% sf$id] # ajouter l'id 984 depuis dbx


sf <- sf %>% filter(id %in% gil$id)

sf <- sf %>% arrange(id)
gil <- gil %>% arrange(id)
gilç_984 <- gil %>% filter(id == 984)
gil <- gil %>% filter(id != 984)
unique(sf$id == gil$id)


sf <- sf %>% mutate(id_n = gil$id_n,
              tx_sp_lvl = gil$tax_sp_level,
              tax_gen = gil$tax_gen,
              tax_fam = gil$tax_fam,
              idtax_f = gil$idtax_f,
              wood_density_mean = gil$wood_density_mean)


sf <- sf %>% select(-c(idmodif_idn,idmodif_geom))


# ajouter l'id 984 depuis dbx
# old_sf <- read_sf(file.choose())
# old_sf <- old_sf %>% filter(id == 984)
# old_sf <- old_sf %>% select(-area)
# old_sf <- old_sf %>% select(-c(taxa_level_succession_guild,stem_diameter_observations))
# 
# names(old_sf)[27]
# names(old_sf) == names(sf)
# old_sf <- sf::st_transform(old_sf, st_crs(sf))
# new <- rbind(sf,old_sf)
# plot(new$geom)
# st_write(new, 'E:/updated_crowns_bouamir.gpkg')
```

